### ISSUE TITLE
address matching

### ISSUE THREAD

**Issue by jmcbroom** [MichiganDataScienceTeam/blight-compliance#1]
hey there,

i heard you all are doing some cool things with matching detroit addresses with python-levenshtein. i'm doing something similar for some text messaging apps here at the city! thought you might want to take a look at this code for a class you might be able to plug into your work.

https://gist.github.com/jmcbroom/afc5cfb3093cf48831c2d94563fafccb

**Comment by the-alex** [comment]
Pretty cool! Thanks for the `gist` -- I'll mirror this in our slack channel. I don't know that I'll have the time this weekend to build this into the script, but another organizer might.

Thanks again -- a hat-tip to you!
